### ISSUE TITLE
 Error: kernel is too old for this kvm-kmod release.

### ISSUE THREAD

**Issue by jackjiaxiong** [nvsofts/kvm-kmod#1]
every version can't running configure on my OS,
[root@dm01 /tmp]# uname -r
3.5.0
[root@dm01 kvm-kmod-stable-2.6.31]# ./configure 
Error: kernel is too old for this kvm-kmod release

**Comment by nvsofts** [comment]
Currently, this repository requires Linux version 3.7(see configure).
Please use after Linux version 3.7.

**Comment by jackjiaxiong** [comment]
[root@localhost ~]# uname -r
3.12.17
[root@localhost kvm-kmod]# ./configure 
[root@localhost kvm-kmod]#  make LINUX=../kvm clean sync all
make -C /lib/modules/3.12.17/build M=`pwd` clean
make[1]: Entering directory `/usr/local/src/linux-3.12.17'
  CLEAN   /root/kvm-kmod/.tmp_versions
make[1]: Leaving directory`/usr/local/src/linux-3.12.17'
./sync -v  for-linus -l ../kvm
make -C /lib/modules/3.12.17/build M=`pwd` \
                LINUXINCLUDE="-I`pwd`/include -I`pwd`/include/uapi -Iinclude \
                         -Iinclude/uapi -Iarch/x86/include -Iarch/x86/include/uapi \
                        -Iinclude/generated/uapi -Iarch/x86/include/generated \
                        -Iarch/x86/include/generated/uapi \
                        -I`pwd`/include-compat -I`pwd`/x86 \
                        -include  include/generated/autoconf.h \
                        -include `pwd`/x86/external-module-compat.h" \
                "$@"
make[1]: Entering directory `/usr/local/src/linux-3.12.17'
  LD      /root/kvm-kmod/x86/built-in.o
  CC [M]  /root/kvm-kmod/x86/svm.o
In file included from /root/kvm-kmod/x86/svm.c:51:
/root/kvm-kmod/include/linux/kvm_host.h: In function ‘kvm_guest_enter’:
/root/kvm-kmod/include/linux/kvm_host.h:821: error: implicit declaration of function ‘context_tracking_cpu_is_enabled’
In file included from /root/kvm-kmod/x86/svm.c:53:
/root/kvm-kmod/x86/irq.h:30:23: error: kvm/iodev.h: No such file or directory
In file included from /root/kvm-kmod/x86/irq.h:31,
                 from /root/kvm-kmod/x86/svm.c:53:
/root/kvm-kmod/x86/ioapic.h: At top level:
/root/kvm-kmod/x86/ioapic.h:72: error: field ‘dev’ has incomplete type
In file included from /root/kvm-kmod/x86/irq.h:32,
                 from /root/kvm-kmod/x86/svm.c:53:
/root/kvm-kmod/x86/lapic.h:23: error: field ‘dev’ has incomplete type
In file included from /root/kvm-kmod/x86/svm.c:53:
/root/kvm-kmod/x86/irq.h:69: error: field ‘dev_master’ has incomplete type
/root/kvm-kmod/x86/irq.h:70: error: field ‘dev_slave’ has incomplete type
/root/kvm-kmod/x86/irq.h:71: error: field ‘dev_eclr’ has incomplete type
In file included from /root/kvm-kmod/x86/svm.c:74:
/root/kvm-kmod/include/asm/virtext.h: In function ‘cpu_vmxoff’:
/root/kvm-kmod/include/asm/virtext.h:78: error: implicit declaration of function ‘cr4_clear_bits’
/root/kvm-kmod/include/asm/virtext.h: In function ‘cpu_vmx_enabled’:
/root/kvm-kmod/include/asm/virtext.h:83: error: implicit declaration of function ‘__read_cr4’
/root/kvm-kmod/x86/svm.c: In function ‘svm_set_cr4’:
/root/kvm-kmod/x86/svm.c:1625: error: implicit declaration of function ‘cr4_read_shadow’
make[3]: *** [/root/kvm-kmod/x86/svm.o] Error 1
make[2]: *** [/root/kvm-kmod/x86] Error 2
make[1]: *** [_module_/root/kvm-kmod] Error 2
make[1]: Leaving directory`/usr/local/src/linux-3.12.17'
make: **\* [all] Error 2

**Comment by nvsofts** [comment]
Keep in mind, this repository is mirror of external repository(git://git.kiszka.org/kvm-kmod.git).
Therefore, it is incompatible to newer version of linux.
